### ISSUE TITLE
ami-1f3e225a not available under community images

### ISSUE THREAD

**Issue by bonya** [wendykan/AWSGPU_DeepLearning#1]

**Comment by wendykan** [comment]
It's available for me. Remember if you're copying the id, remove that last space. 
![image](https://cloud.githubusercontent.com/assets/912546/5884949/6554b854-a319-11e4-8a40-d3011c1cc843.png)

**Comment by william-r-s** [comment]
Availability might depend on the currently selected region. I see it when my region is set to US West (N. California), but not when set to US East (N. Virginia)

**Comment by someoneAlready** [comment]
I cannot find, even when my region is set to N. California, T_T

**Comment by shushi2016** [comment]
Same here. I can't find it, no matter whether I choose N. California or Oregon.
